from app import add_ing_to_drink 

add_ing_to_drink('Champagne Cocktail','Champagne')
add_ing_to_drink('Champagne Cocktail','Simple Syrup')
add_ing_to_drink('Champagne Cocktail','Bitters')
add_ing_to_drink('Cuba Libre','Rum')
add_ing_to_drink('Cuba Libre','Lime')
add_ing_to_drink('Cuba Libre','Coke')
add_ing_to_drink('Daiquiri','Rum')
add_ing_to_drink('Daiquiri','Lime')
add_ing_to_drink('Daiquiri','Simple Syrup')
add_ing_to_drink('Gimlet','Gin')
add_ing_to_drink('Gimlet','Lime')
add_ing_to_drink('Gimlet','Simple Syrup')
add_ing_to_drink('Gin Buck','Gin')
add_ing_to_drink('Gin Buck','Lemon')
add_ing_to_drink('Gin Buck','Ginger Ale')
add_ing_to_drink('Old Fashioned','Whiskey')
add_ing_to_drink('Old Fashioned','Simple Syrup')
add_ing_to_drink('Old Fashioned','Bitters')
add_ing_to_drink('Planter\'s Punch','Rum')
add_ing_to_drink('Planter\'s Punch','Lime')
add_ing_to_drink('Planter\'s Punch','Simple Syrup')
add_ing_to_drink('Rum Old Fashioned','Rum')
add_ing_to_drink('Rum Old Fashioned','Simple Syrup')
add_ing_to_drink('Rum Old Fashioned','Bitters')
add_ing_to_drink('Tequila Old Fashioned','Tequila')
add_ing_to_drink('Tequila Old Fashioned','Simple Syrup')
add_ing_to_drink('Tequila Old Fashioned','Bitters')
add_ing_to_drink('Gin & Orange Juice','Gin')
add_ing_to_drink('Gin & Orange Juice','Orange')
add_ing_to_drink('Gin','Soda Water')
add_ing_to_drink('Gin Highball','Gin')
add_ing_to_drink('Gin Highball','Ginger Ale')
add_ing_to_drink('Mexican Screw','Tequila')
add_ing_to_drink('Mexican Screw','Orange')
add_ing_to_drink('Mexicola','Tequila')
add_ing_to_drink('Mexicola','Coke')
add_ing_to_drink('Mimosa','Champagne')
add_ing_to_drink('Mimosa','Orange')
add_ing_to_drink('Rum & Orange Juice','Rum')
add_ing_to_drink('Rum & Orange Juice','Orange')
add_ing_to_drink('Rum & Pineapple Juice','Rum')
add_ing_to_drink('Rum & Pineapple Juice','Pineapple')
add_ing_to_drink('Rum and Coke','Rum')
add_ing_to_drink('Rum and Coke','Coke')
add_ing_to_drink('Rum and Tonic','Rum')
add_ing_to_drink('Rum and Tonic','Soda Water')
add_ing_to_drink('Rum Highball','Rum')
add_ing_to_drink('Rum Highball','Ginger Ale')
add_ing_to_drink('Screwdriver','Vodka')
add_ing_to_drink('Screwdriver','Orange')
add_ing_to_drink('Vodka Tonic','Vodka')
add_ing_to_drink('Vodka Tonic','Soda Water')
add_ing_to_drink('Vodka Gimlet','Vodka')
add_ing_to_drink('Vodka Gimlet','Lime')
add_ing_to_drink('Vodka Gimlet','Simple Syrup')
add_ing_to_drink('Vodka Highball','Vodka')
add_ing_to_drink('Vodka Highball','Ginger Ale')
add_ing_to_drink('Whiskey & Cola','Whiskey')
add_ing_to_drink('Whiskey & Cola','Coke')
add_ing_to_drink('Whiskey Highball','Whiskey')
add_ing_to_drink('Whiskey Highball','Ginger Ale')